import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import { Header } from "@/components";

const roboto = Roboto({ 
  weight:'400',
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className + 'w-screen h-screen'}>
        <Header/>
        <main className="container mx-auto p-3">{children}</main></body>
    </html>
  );
}
